/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_cognito_identity_pool_id: "us-east-1:bf95ecdf-441f-40cf-ba7e-177ac3701192",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_qeGRMQZlu",
	aws_user_pools_web_client_id: "5pjre1eoogqd5mdt3eo7i4m5b2",
	oauth: {
		domain: "techzilla6ae6c328-6ae6c328-dev.auth.us-east-1.amazoncognito.com",
		scope: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
		redirectSignIn: "http://localhost:3000/", //
		redirectSignOut: "http://localhost:3000/",
		responseType: "code",
	},
	federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
